MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  META_ARCHITECTURE: "GeneralizedRCNNMultiTask"
  BACKBONE:
    NAME: "build_resnet_fpn_backbone"
  RESNETS:
    OUT_FEATURES: ["res2", "res3", "res4", "res5"]
  FPN:
    IN_FEATURES: ["res2", "res3", "res4", "res5"]
  ANCHOR_GENERATOR:
    SIZES: [[32], [64], [128], [256], [512]]  # One size for each in feature map
    ASPECT_RATIOS: [[0.5, 1.0, 2.0]]  # Three aspect ratios (same for all in feature maps)
  RPN:
    IN_FEATURES: ["p2", "p3", "p4", "p5", "p6"]
    PRE_NMS_TOPK_TRAIN: 2000  # Per FPN level
    PRE_NMS_TOPK_TEST: 1000  # Per FPN level
    # Detectron1 uses 2000 proposals per-batch,
    # (See "modeling/rpn/rpn_outputs.py" for details of this legacy issue)
    # which is approximately 1000 proposals per-image since the default batch size for FPN is 2.
    POST_NMS_TOPK_TRAIN: 1000
    POST_NMS_TOPK_TEST: 1000
  ROI_HEADS:
    NAME: "StandardROIHeads"
    IN_FEATURES: ["p2", "p3", "p4", "p5"]
    NUM_CLASSES: 10   # Number of foreground classes
  ROI_BOX_HEAD:
    NAME: "FastRCNNConvFCHead"
    NUM_FC: 2
    POOLER_RESOLUTION: 7
  MULTI_TASK_ON: True
  MULTI_TASK:
    DETECTION_ON: True
    CLASSIFICATION_ON: True
    CLASSIFICATION_IN_FEATURES: ["p3"]
    SEGMENTATION_ON: True
    SEGMENTATION_IN_FEATURES: ["p4"]
DATASETS:
  TRAIN: ("voc_al_train", )
  TEST: ("voc_al_test",)
SOLVER:
  IMS_PER_BATCH: 4
  BASE_LR: 0.005
  STEPS: (60000, 80000)
  MAX_ITER: 90000
  WARMUP_FACTOR: 0.1
INPUT:
  # Size of the smallest side of the image during training
  MIN_SIZE_TRAIN: (800,)
  # Maximum size of the side of the image during training
  MAX_SIZE_TRAIN: 1333
  # Size of the smallest side of the image during testing. Set to zero to disable resize in testing.
  MIN_SIZE_TEST: 800
  # Maximum size of the side of the image during testing
  MAX_SIZE_TEST: 1333

OUTPUT_DIR: "./output/model_test_multi/"

